name: S3 Sync

on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync S3 bucket
      run: |
        aws s3 sync ./lambda/ s3://${{ secrets.S3_BUCKET_LAMBDA }} --delete
        cd lambda/
        zip -r chat_lambda.zip chat_lambda.py
        aws s3 cp chat_lambda.zip s3://${{ secrets.S3_BUCKET_LAMBDA }}/chat_lambda.zip --metadata hash="$(shell openssl dgst -binary -sha256 $(ZIP_NAME) | openssl base64)"


      
